version: '3.4'

services:
  testdeployblazor:
    image: testdeployblazor:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Maps TCP port 80 in the container to port 8000 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - webnet

networks:
  webnet:
