version: '3.4'

services:
  testdeployblazor:
    image: testdeployblazor:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - webnet

networks:
  webnet:
