version: '3.4'

services:
  testdeployblazor:
    image: testdeployblazor
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH=1
